"""
Generate 50 encounters per category with 3 words each.
Each encounter is a realistic scenario an expat would face in South America.
"""

# 50 encounters per category with 3 words each
ENCOUNTERS_BY_CATEGORY = {
    "airport": [
        # 1-10: Check-in and boarding
        {"title": "Checking in at the Airport – 1", "words": ["vuelo", "pasaporte", "maleta"]},
        {"title": "Checking in at the Airport – 2", "words": ["equipaje", "salida", "asiento"]},
        {"title": "Checking in at the Airport – 3", "words": ["boleto", "terminal", "puerta"]},
        {"title": "Checking in at the Airport – 4", "words": ["hora", "retraso", "vuelo"]},
        {"title": "Checking in at the Airport – 5", "words": ["peso", "maleta", "equipaje"]},
        {"title": "Checking in at the Airport – 6", "words": ["documento", "identificación", "pasaporte"]},
        {"title": "Checking in at the Airport – 7", "words": ["ventanilla", "mostrador", "vuelo"]},
        {"title": "Checking in at the Airport – 8", "words": ["reserva", "confirmación", "boleto"]},
        {"title": "Checking in at the Airport – 9", "words": ["clase", "asiento", "ventana"]},
        {"title": "Checking in at the Airport – 10", "words": ["conexión", "escala", "vuelo"]},
        # 11-20: Security and customs
        {"title": "Going Through Security – 1", "words": ["seguridad", "control", "equipaje"]},
        {"title": "Going Through Security – 2", "words": ["líquido", "bolsa", "prohibido"]},
        {"title": "Going Through Security – 3", "words": ["cinturón", "zapatos", "seguridad"]},
        {"title": "Going Through Security – 4", "words": ["computadora", "tableta", "equipaje"]},
        {"title": "Going Through Security – 5", "words": ["metal", "detector", "seguridad"]},
        {"title": "Customs Declaration – 1", "words": ["aduana", "declaración", "artículo"]},
        {"title": "Customs Declaration – 2", "words": ["valor", "producto", "aduana"]},
        {"title": "Customs Declaration – 3", "words": ["prohibido", "alimento", "aduana"]},
        {"title": "Customs Declaration – 4", "words": ["dólar", "efectivo", "declaración"]},
        {"title": "Customs Declaration – 5", "words": ["formulario", "firma", "aduana"]},
        # 21-30: Gate and boarding
        {"title": "Finding Your Gate – 1", "words": ["puerta", "salida", "número"]},
        {"title": "Finding Your Gate – 2", "words": ["pantalla", "información", "vuelo"]},
        {"title": "Finding Your Gate – 3", "words": ["cambio", "puerta", "anuncio"]},
        {"title": "Boarding the Plane – 1", "words": ["abordar", "embarque", "zona"]},
        {"title": "Boarding the Plane – 2", "words": ["grupo", "número", "abordar"]},
        {"title": "Boarding the Plane – 3", "words": ["tarjeta", "embarque", "mostrar"]},
        {"title": "On the Plane – 1", "words": ["asiento", "maleta", "compartimiento"]},
        {"title": "On the Plane – 2", "words": ["cinturón", "seguridad", "asiento"]},
        {"title": "On the Plane – 3", "words": ["sobrecargo", "ayuda", "asiento"]},
        {"title": "On the Plane – 4", "words": ["comida", "bebida", "servicio"]},
        # 31-40: Arrival and baggage
        {"title": "Arriving at Destination – 1", "words": ["llegada", "aeropuerto", "hora"]},
        {"title": "Arriving at Destination – 2", "words": ["inmigración", "pasaporte", "sello"]},
        {"title": "Arriving at Destination – 3", "words": ["visa", "permiso", "documento"]},
        {"title": "Collecting Baggage – 1", "words": ["equipaje", "cinta", "número"]},
        {"title": "Collecting Baggage – 2", "words": ["maleta", "perdida", "reclamación"]},
        {"title": "Collecting Baggage – 3", "words": ["carrito", "equipaje", "ayuda"]},
        {"title": "Collecting Baggage – 4", "words": ["daño", "maleta", "reclamación"]},
        {"title": "Leaving the Airport – 1", "words": ["taxi", "transporte", "salida"]},
        {"title": "Leaving the Airport – 2", "words": ["dirección", "hotel", "taxi"]},
        {"title": "Leaving the Airport – 3", "words": ["precio", "tarifa", "taxi"]},
        # 41-50: Special situations
        {"title": "Lost Luggage – 1", "words": ["maleta", "perdida", "oficina"]},
        {"title": "Lost Luggage – 2", "words": ["reclamación", "formulario", "maleta"]},
        {"title": "Missed Flight – 1", "words": ["vuelo", "perdido", "siguiente"]},
        {"title": "Missed Flight – 2", "words": ["cambio", "vuelo", "costo"]},
        {"title": "Flight Delay – 1", "words": ["retraso", "vuelo", "tiempo"]},
        {"title": "Flight Delay – 2", "words": ["espera", "sala", "información"]},
        {"title": "Upgrade Request – 1", "words": ["clase", "mejor", "disponible"]},
        {"title": "Upgrade Request – 2", "words": ["precio", "upgrade", "asiento"]},
        {"title": "Special Assistance – 1", "words": ["ayuda", "silla", "ruedas"]},
        {"title": "Special Assistance – 2", "words": ["asistencia", "necesidad", "ayuda"]},
    ],
    
    "banking": [
        # 1-10: Basic transactions
        {"title": "Withdrawing Cash – 1", "words": ["cajero", "efectivo", "tarjeta"]},
        {"title": "Withdrawing Cash – 2", "words": ["retirar", "dinero", "cajero"]},
        {"title": "Withdrawing Cash – 3", "words": ["monto", "cantidad", "efectivo"]},
        {"title": "Depositing Money – 1", "words": ["depositar", "dinero", "cuenta"]},
        {"title": "Depositing Money – 2", "words": ["cheque", "depósito", "banco"]},
        {"title": "Checking Balance – 1", "words": ["saldo", "cuenta", "consultar"]},
        {"title": "Checking Balance – 2", "words": ["movimiento", "cuenta", "extracto"]},
        {"title": "Transferring Money – 1", "words": ["transferencia", "cuenta", "monto"]},
        {"title": "Transferring Money – 2", "words": ["enviar", "dinero", "cuenta"]},
        {"title": "Paying Bills – 1", "words": ["pagar", "factura", "servicio"]},
        # 11-20: Card issues
        {"title": "Card Not Working – 1", "words": ["tarjeta", "problema", "no"]},
        {"title": "Card Not Working – 2", "words": ["bloqueada", "tarjeta", "desbloquear"]},
        {"title": "Card Not Working – 3", "words": ["rechazada", "tarjeta", "razón"]},
        {"title": "Lost Card – 1", "words": ["tarjeta", "perdida", "bloquear"]},
        {"title": "Lost Card – 2", "words": ["reportar", "tarjeta", "nueva"]},
        {"title": "Stolen Card – 1", "words": ["tarjeta", "robada", "urgente"]},
        {"title": "Card Expired – 1", "words": ["vencida", "tarjeta", "renovar"]},
        {"title": "Card Limit – 1", "words": ["límite", "tarjeta", "aumentar"]},
        {"title": "Card Pin – 1", "words": ["pin", "cambiar", "tarjeta"]},
        {"title": "Card Pin – 2", "words": ["olvidé", "pin", "recuperar"]},
        # 21-30: Account management
        {"title": "Opening Account – 1", "words": ["abrir", "cuenta", "documento"]},
        {"title": "Opening Account – 2", "words": ["requisito", "cuenta", "necesario"]},
        {"title": "Closing Account – 1", "words": ["cerrar", "cuenta", "proceso"]},
        {"title": "Changing Address – 1", "words": ["dirección", "cambiar", "actualizar"]},
        {"title": "Changing Phone – 1", "words": ["teléfono", "cambiar", "número"]},
        {"title": "Account Statement – 1", "words": ["extracto", "cuenta", "mes"]},
        {"title": "Account Statement – 2", "words": ["estado", "cuenta", "imprimir"]},
        {"title": "Online Banking – 1", "words": ["banca", "en línea", "acceso"]},
        {"title": "Online Banking – 2", "words": ["usuario", "contraseña", "olvidé"]},
        {"title": "Mobile Banking – 1", "words": ["aplicación", "móvil", "instalar"]},
        # 31-40: Currency and exchange
        {"title": "Currency Exchange – 1", "words": ["cambio", "moneda", "dólar"]},
        {"title": "Currency Exchange – 2", "words": ["tasa", "cambio", "precio"]},
        {"title": "Currency Exchange – 3", "words": ["pesos", "dólares", "cambiar"]},
        {"title": "Traveler's Check – 1", "words": ["cheque", "viajero", "cambiar"]},
        {"title": "Foreign Currency – 1", "words": ["moneda", "extranjera", "depositar"]},
        {"title": "Exchange Rate – 1", "words": ["tasa", "cambio", "hoy"]},
        {"title": "Exchange Rate – 2", "words": ["mejor", "tasa", "dónde"]},
        {"title": "Large Amount – 1", "words": ["cantidad", "grande", "notificar"]},
        {"title": "Large Amount – 2", "words": ["límite", "transacción", "aumentar"]},
        {"title": "Currency Fee – 1", "words": ["comisión", "cambio", "costo"]},
        # 41-50: Loans and services
        {"title": "Loan Application – 1", "words": ["préstamo", "solicitar", "requisito"]},
        {"title": "Loan Application – 2", "words": ["interés", "tasa", "préstamo"]},
        {"title": "Credit Card – 1", "words": ["tarjeta", "crédito", "solicitar"]},
        {"title": "Credit Card – 2", "words": ["límite", "crédito", "aumentar"]},
        {"title": "Debit Card – 1", "words": ["tarjeta", "débito", "solicitar"]},
        {"title": "Safe Deposit Box – 1", "words": ["caja", "seguridad", "alquilar"]},
        {"title": "Bank Transfer Fee – 1", "words": ["comisión", "transferencia", "costo"]},
        {"title": "Account Fee – 1", "words": ["comisión", "cuenta", "mensual"]},
        {"title": "Bank Hours – 1", "words": ["horario", "banco", "abierto"]},
        {"title": "Bank Location – 1", "words": ["sucursal", "cerca", "dirección"]},
    ],
    
    "clothing": [
        # 1-10: Finding items
        {"title": "Finding Your Size – 1", "words": ["talla", "tamaño", "tengo"]},
        {"title": "Finding Your Size – 2", "words": ["medida", "talla", "equivalente"]},
        {"title": "Finding Your Size – 3", "words": ["pequeño", "grande", "talla"]},
        {"title": "Looking for Shirt – 1", "words": ["camisa", "buscar", "color"]},
        {"title": "Looking for Pants – 1", "words": ["pantalón", "buscar", "talla"]},
        {"title": "Looking for Shoes – 1", "words": ["zapatos", "número", "talla"]},
        {"title": "Looking for Dress – 1", "words": ["vestido", "talla", "color"]},
        {"title": "Looking for Jacket – 1", "words": ["chaqueta", "talla", "abrigo"]},
        {"title": "Looking for Jeans – 1", "words": ["jeans", "pantalón", "talla"]},
        {"title": "Looking for Shorts – 1", "words": ["pantalones", "cortos", "talla"]},
        # 11-20: Trying on
        {"title": "Trying On Clothes – 1", "words": ["probar", "ropa", "probador"]},
        {"title": "Trying On Clothes – 2", "words": ["vestidor", "probar", "dónde"]},
        {"title": "Trying On Clothes – 3", "words": ["espejo", "probar", "ver"]},
        {"title": "Size Too Small – 1", "words": ["pequeño", "talla", "grande"]},
        {"title": "Size Too Big – 1", "words": ["grande", "talla", "pequeño"]},
        {"title": "Different Color – 1", "words": ["color", "diferente", "tener"]},
        {"title": "Different Style – 1", "words": ["estilo", "diferente", "mostrar"]},
        {"title": "Doesn't Fit – 1", "words": ["no", "queda", "bien"]},
        {"title": "Perfect Fit – 1", "words": ["perfecto", "talla", "quedarse"]},
        {"title": "Need Help – 1", "words": ["ayuda", "necesito", "talla"]},
        # 21-30: Prices and payment
        {"title": "Asking Price – 1", "words": ["precio", "cuánto", "cuesta"]},
        {"title": "Asking Price – 2", "words": ["costo", "precio", "barato"]},
        {"title": "On Sale – 1", "words": ["rebaja", "descuento", "precio"]},
        {"title": "Discount – 1", "words": ["descuento", "porcentaje", "precio"]},
        {"title": "Final Price – 1", "words": ["precio", "final", "total"]},
        {"title": "Payment Method – 1", "words": ["pagar", "tarjeta", "efectivo"]},
        {"title": "Credit Card – 1", "words": ["tarjeta", "crédito", "aceptar"]},
        {"title": "Cash Payment – 1", "words": ["efectivo", "pagar", "cambio"]},
        {"title": "Receipt – 1", "words": ["recibo", "factura", "necesito"]},
        {"title": "Return Policy – 1", "words": ["devolver", "política", "días"]},
        # 31-40: Special requests
        {"title": "Alterations – 1", "words": ["arreglar", "ajustar", "talla"]},
        {"title": "Alterations – 2", "words": ["cortar", "largo", "pantalón"]},
        {"title": "Gift Wrapping – 1", "words": ["envolver", "regalo", "papel"]},
        {"title": "Gift Receipt – 1", "words": ["recibo", "regalo", "sin"]},
        {"title": "Gift Card – 1", "words": ["tarjeta", "regalo", "comprar"]},
        {"title": "Store Credit – 1", "words": ["crédito", "tienda", "devolución"]},
        {"title": "Exchange Item – 1", "words": ["cambiar", "artículo", "talla"]},
        {"title": "Exchange Item – 2", "words": ["devolver", "cambiar", "talla"]},
        {"title": "Store Hours – 1", "words": ["horario", "tienda", "abierto"]},
        {"title": "Store Location – 1", "words": ["sucursal", "otra", "dirección"]},
        # 41-50: Quality and materials
        {"title": "Material Question – 1", "words": ["material", "tela", "algodón"]},
        {"title": "Material Question – 2", "words": ["sintético", "natural", "material"]},
        {"title": "Washing Instructions – 1", "words": ["lavar", "instrucciones", "etiqueta"]},
        {"title": "Washing Instructions – 2", "words": ["secadora", "lavar", "agua"]},
        {"title": "Quality Check – 1", "words": ["calidad", "buena", "duradero"]},
        {"title": "Quality Check – 2", "words": ["resistente", "calidad", "material"]},
        {"title": "Warranty – 1", "words": ["garantía", "año", "cubrir"]},
        {"title": "Warranty – 2", "words": ["defecto", "garantía", "cambiar"]},
        {"title": "Brand Question – 1", "words": ["marca", "fabricante", "país"]},
        {"title": "Brand Question – 2", "words": ["importado", "local", "marca"]},
    ],
    
    "internet": [
        # 1-10: WiFi setup
        {"title": "WiFi Not Working – 1", "words": ["wifi", "internet", "no"]},
        {"title": "WiFi Not Working – 2", "words": ["conexión", "perdida", "internet"]},
        {"title": "WiFi Password – 1", "words": ["contraseña", "wifi", "cual"]},
        {"title": "WiFi Password – 2", "words": ["clave", "wifi", "necesito"]},
        {"title": "WiFi Slow – 1", "words": ["lento", "internet", "velocidad"]},
        {"title": "WiFi Slow – 2", "words": ["rápido", "internet", "mejorar"]},
        {"title": "WiFi Range – 1", "words": ["señal", "débil", "wifi"]},
        {"title": "WiFi Range – 2", "words": ["alcance", "wifi", "extender"]},
        {"title": "Router Problem – 1", "words": ["router", "problema", "reiniciar"]},
        {"title": "Router Problem – 2", "words": ["modem", "no", "funciona"]},
        # 11-20: Phone plans
        {"title": "Phone Plan – 1", "words": ["plan", "teléfono", "datos"]},
        {"title": "Phone Plan – 2", "words": ["minutos", "plan", "incluir"]},
        {"title": "Phone Plan – 3", "words": ["datos", "internet", "plan"]},
        {"title": "Prepaid Card – 1", "words": ["recarga", "tarjeta", "saldo"]},
        {"title": "Prepaid Card – 2", "words": ["prepago", "recargar", "dónde"]},
        {"title": "Phone Unlocked – 1", "words": ["desbloqueado", "teléfono", "chip"]},
        {"title": "Phone Unlocked – 2", "words": ["chip", "sim", "activar"]},
        {"title": "International Calls – 1", "words": ["llamada", "internacional", "costo"]},
        {"title": "International Calls – 2", "words": ["minutos", "internacional", "plan"]},
        {"title": "Roaming – 1", "words": ["roaming", "datos", "activar"]},
        # 21-30: Service issues
        {"title": "No Service – 1", "words": ["señal", "no", "teléfono"]},
        {"title": "No Service – 2", "words": ["cobertura", "zona", "señal"]},
        {"title": "Dropped Call – 1", "words": ["llamada", "cortada", "problema"]},
        {"title": "Dropped Call – 2", "words": ["señal", "perdida", "llamada"]},
        {"title": "Slow Internet – 1", "words": ["lento", "internet", "velocidad"]},
        {"title": "Slow Internet – 2", "words": ["carga", "página", "lenta"]},
        {"title": "No Internet – 1", "words": ["internet", "no", "funciona"]},
        {"title": "No Internet – 2", "words": ["conexión", "perdida", "restaurar"]},
        {"title": "Billing Issue – 1", "words": ["factura", "cobro", "error"]},
        {"title": "Billing Issue – 2", "words": ["cargo", "incorrecto", "factura"]},
        # 31-40: Technician visits
        {"title": "Technician Visit – 1", "words": ["técnico", "visita", "cita"]},
        {"title": "Technician Visit – 2", "words": ["reparar", "internet", "técnico"]},
        {"title": "Technician Visit – 3", "words": ["instalar", "servicio", "técnico"]},
        {"title": "Technician Visit – 4", "words": ["cable", "problema", "técnico"]},
        {"title": "Technician Visit – 5", "words": ["equipo", "reemplazar", "técnico"]},
        {"title": "Installation – 1", "words": ["instalar", "servicio", "cuándo"]},
        {"title": "Installation – 2", "words": ["instalación", "costo", "gratis"]},
        {"title": "Equipment Problem – 1", "words": ["equipo", "malo", "cambiar"]},
        {"title": "Equipment Problem – 2", "words": ["router", "nuevo", "necesito"]},
        {"title": "Equipment Problem – 3", "words": ["modem", "reemplazar", "garantía"]},
        # 41-50: Account and support
        {"title": "Account Setup – 1", "words": ["cuenta", "crear", "usuario"]},
        {"title": "Account Setup – 2", "words": ["registrar", "servicio", "datos"]},
        {"title": "Password Reset – 1", "words": ["contraseña", "olvidé", "recuperar"]},
        {"title": "Password Reset – 2", "words": ["clave", "restablecer", "email"]},
        {"title": "Customer Service – 1", "words": ["atención", "cliente", "hablar"]},
        {"title": "Customer Service – 2", "words": ["soporte", "técnico", "ayuda"]},
        {"title": "Cancel Service – 1", "words": ["cancelar", "servicio", "cuándo"]},
        {"title": "Cancel Service – 2", "words": ["terminar", "contrato", "penalización"]},
        {"title": "Upgrade Service – 1", "words": ["mejorar", "plan", "velocidad"]},
        {"title": "Upgrade Service – 2", "words": ["aumentar", "datos", "plan"]},
    ],
    
    "small_talk": [
        # 1-10: Greetings and introductions
        {"title": "Meeting Someone New – 1", "words": ["hola", "mucho gusto", "nombre"]},
        {"title": "Meeting Someone New – 2", "words": ["nombre", "llamo", "tú"]},
        {"title": "Meeting Someone New – 3", "words": ["presentar", "amigo", "conocer"]},
        {"title": "Asking How They Are – 1", "words": ["cómo", "estás", "bien"]},
        {"title": "Asking How They Are – 2", "words": ["qué", "tal", "bien"]},
        {"title": "Responding to Greeting – 1", "words": ["bien", "gracias", "tú"]},
        {"title": "Responding to Greeting – 2", "words": ["muy", "bien", "gracias"]},
        {"title": "Saying Goodbye – 1", "words": ["adiós", "hasta luego", "pronto"]},
        {"title": "Saying Goodbye – 2", "words": ["nos vemos", "pronto", "chao"]},
        {"title": "Saying Goodbye – 3", "words": ["chao", "cuídate", "adiós"]},
        # 11-20: Where are you from
        {"title": "Where Are You From – 1", "words": ["de", "dónde", "eres"]},
        {"title": "Where Are You From – 2", "words": ["país", "vienes", "cuál"]},
        {"title": "Where Are You From – 3", "words": ["nacionalidad", "cuál", "tú"]},
        {"title": "Talking About Origin – 1", "words": ["soy", "de", "país"]},
        {"title": "Talking About Origin – 2", "words": ["vengo", "de", "ciudad"]},
        {"title": "Talking About Origin – 3", "words": ["nací", "en", "país"]},
        {"title": "How Long Here – 1", "words": ["cuánto", "tiempo", "aquí"]},
        {"title": "How Long Here – 2", "words": ["vives", "aquí", "años"]},
        {"title": "How Long Here – 3", "words": ["llegaste", "cuándo", "aquí"]},
        {"title": "Do You Like It Here – 1", "words": ["me gusta", "aquí", "país"]},
        # 21-30: Work and occupation
        {"title": "What Do You Do – 1", "words": ["qué", "haces", "trabajo"]},
        {"title": "What Do You Do – 2", "words": ["trabajo", "cuál", "tú"]},
        {"title": "What Do You Do – 3", "words": ["trabajas", "dónde", "qué"]},
        {"title": "Talking About Work – 1", "words": ["trabajo", "como", "profesión"]},
        {"title": "Talking About Work – 2", "words": ["soy", "profesor", "ingeniero"]},
        {"title": "Talking About Work – 3", "words": ["empresa", "trabajo", "dónde"]},
        {"title": "Do You Like Your Job – 1", "words": ["me gusta", "trabajo", "profesión"]},
        {"title": "Do You Like Your Job – 2", "words": ["satisfecho", "trabajo", "contento"]},
        {"title": "Work Schedule – 1", "words": ["horario", "trabajo", "cuándo"]},
        {"title": "Work Schedule – 2", "words": ["días", "trabajas", "semana"]},
        # 31-40: Family and personal
        {"title": "Do You Have Family – 1", "words": ["tienes", "familia", "aquí"]},
        {"title": "Do You Have Family – 2", "words": ["esposa", "hijos", "tienes"]},
        {"title": "Talking About Family – 1", "words": ["tengo", "hijos", "esposa"]},
        {"title": "Talking About Family – 2", "words": ["viven", "familia", "dónde"]},
        {"title": "Hobbies – 1", "words": ["qué", "haces", "tiempo"]},
        {"title": "Hobbies – 2", "words": ["pasatiempo", "gusta", "hacer"]},
        {"title": "Hobbies – 3", "words": ["deporte", "música", "gusta"]},
        {"title": "Weekend Plans – 1", "words": ["planes", "fin", "semana"]},
        {"title": "Weekend Plans – 2", "words": ["qué", "vas", "hacer"]},
        {"title": "Weekend Plans – 3", "words": ["descansar", "salir", "planes"]},
        # 41-50: Weather and general
        {"title": "Talking About Weather – 1", "words": ["tiempo", "hace", "calor"]},
        {"title": "Talking About Weather – 2", "words": ["lluvia", "sol", "tiempo"]},
        {"title": "Talking About Weather – 3", "words": ["frío", "calor", "temperatura"]},
        {"title": "How's Your Day – 1", "words": ["cómo", "día", "fue"]},
        {"title": "How's Your Day – 2", "words": ["bien", "mal", "día"]},
        {"title": "Compliment – 1", "words": ["bonito", "lindo", "gusta"]},
        {"title": "Compliment – 2", "words": ["bien", "hecho", "felicidades"]},
        {"title": "Apology – 1", "words": ["perdón", "disculpa", "lo"]},
        {"title": "Apology – 2", "words": ["siento", "mucho", "perdón"]},
        {"title": "Thank You – 1", "words": ["gracias", "mucho", "ayuda"]},
    ],
    
    "contractor": [
        # 1-10: Initial contact
        {"title": "Hiring a Contractor – 1", "words": ["contratista", "necesito", "trabajo"]},
        {"title": "Hiring a Contractor – 2", "words": ["obra", "reparación", "casa"]},
        {"title": "Getting a Quote – 1", "words": ["presupuesto", "costo", "cuánto"]},
        {"title": "Getting a Quote – 2", "words": ["cotización", "precio", "trabajo"]},
        {"title": "Describing the Work – 1", "words": ["necesito", "hacer", "casa"]},
        {"title": "Describing the Work – 2", "words": ["reparar", "arreglar", "problema"]},
        {"title": "When Can You Start – 1", "words": ["cuándo", "empezar", "trabajo"]},
        {"title": "When Can You Start – 2", "words": ["disponible", "fecha", "comenzar"]},
        {"title": "How Long Will It Take – 1", "words": ["cuánto", "tiempo", "tardar"]},
        {"title": "How Long Will It Take – 2", "words": ["días", "semanas", "terminar"]},
        # 11-20: Materials and supplies
        {"title": "Materials Needed – 1", "words": ["material", "necesario", "qué"]},
        {"title": "Materials Needed – 2", "words": ["comprar", "material", "quién"]},
        {"title": "Material Cost – 1", "words": ["costo", "material", "incluido"]},
        {"title": "Material Cost – 2", "words": ["precio", "material", "separado"]},
        {"title": "Quality of Materials – 1", "words": ["calidad", "material", "buena"]},
        {"title": "Quality of Materials – 2", "words": ["barato", "caro", "calidad"]},
        {"title": "Where to Buy – 1", "words": ["dónde", "comprar", "material"]},
        {"title": "Where to Buy – 2", "words": ["ferretería", "tienda", "material"]},
        {"title": "Delivery of Materials – 1", "words": ["entrega", "material", "cuándo"]},
        {"title": "Delivery of Materials – 2", "words": ["traer", "material", "casa"]},
        # 21-30: Specific work types
        {"title": "Plumbing Work – 1", "words": ["plomería", "problema", "agua"]},
        {"title": "Plumbing Work – 2", "words": ["fuga", "caño", "reparar"]},
        {"title": "Electrical Work – 1", "words": ["eléctrico", "problema", "luz"]},
        {"title": "Electrical Work – 2", "words": ["cable", "cortocircuito", "reparar"]},
        {"title": "Painting – 1", "words": ["pintar", "casa", "pared"]},
        {"title": "Painting – 2", "words": ["pintura", "color", "cuarto"]},
        {"title": "Tiling – 1", "words": ["azulejo", "poner", "baño"]},
        {"title": "Tiling – 2", "words": ["baldosa", "cocina", "instalar"]},
        {"title": "Carpentry – 1", "words": ["carpintería", "mueble", "hacer"]},
        {"title": "Carpentry – 2", "words": ["madera", "estante", "construir"]},
        # 31-40: Payment and schedule
        {"title": "Payment Terms – 1", "words": ["pago", "cuándo", "cómo"]},
        {"title": "Payment Terms – 2", "words": ["anticipo", "final", "pago"]},
        {"title": "Payment Method – 1", "words": ["efectivo", "cheque", "transferencia"]},
        {"title": "Payment Method – 2", "words": ["tarjeta", "aceptar", "pago"]},
        {"title": "Work Schedule – 1", "words": ["horario", "trabajar", "días"]},
        {"title": "Work Schedule – 2", "words": ["empezar", "terminar", "hora"]},
        {"title": "Work Schedule – 3", "words": ["fines", "semana", "trabajar"]},
        {"title": "Delays – 1", "words": ["retraso", "trabajo", "cuándo"]},
        {"title": "Delays – 2", "words": ["demora", "material", "esperar"]},
        {"title": "Completion Date – 1", "words": ["terminar", "fecha", "cuándo"]},
        # 41-50: Problems and warranty
        {"title": "Problem with Work – 1", "words": ["problema", "trabajo", "mal"]},
        {"title": "Problem with Work – 2", "words": ["arreglar", "mal", "hacer"]},
        {"title": "Warranty – 1", "words": ["garantía", "trabajo", "años"]},
        {"title": "Warranty – 2", "words": ["cubrir", "garantía", "problema"]},
        {"title": "Clean Up – 1", "words": ["limpiar", "después", "trabajo"]},
        {"title": "Clean Up – 2", "words": ["basura", "material", "quitar"]},
        {"title": "Permits – 1", "words": ["permiso", "necesario", "obra"]},
        {"title": "Permits – 2", "words": ["licencia", "municipal", "obtener"]},
        {"title": "Insurance – 1", "words": ["seguro", "trabajo", "tener"]},
        {"title": "Insurance – 2", "words": ["responsabilidad", "seguro", "cubrir"]},
    ],
    
    "groceries": [
        # 1-10: Finding items
        {"title": "Looking for Produce – 1", "words": ["fruta", "verdura", "dónde"]},
        {"title": "Looking for Produce – 2", "words": ["tomate", "lechuga", "buscar"]},
        {"title": "Looking for Meat – 1", "words": ["carne", "pollo", "dónde"]},
        {"title": "Looking for Meat – 2", "words": ["pescado", "carne", "fresco"]},
        {"title": "Looking for Dairy – 1", "words": ["leche", "queso", "dónde"]},
        {"title": "Looking for Dairy – 2", "words": ["yogur", "mantequilla", "buscar"]},
        {"title": "Looking for Bread – 1", "words": ["pan", "dónde", "fresco"]},
        {"title": "Looking for Bread – 2", "words": ["panadería", "pan", "buscar"]},
        {"title": "Looking for Spices – 1", "words": ["especia", "condimento", "dónde"]},
        {"title": "Looking for Spices – 2", "words": ["sal", "pimienta", "buscar"]},
        # 11-20: Asking for items
        {"title": "Asking for Quantity – 1", "words": ["cuánto", "kilo", "necesito"]},
        {"title": "Asking for Quantity – 2", "words": ["medio", "kilo", "gramo"]},
        {"title": "Asking for Specific Item – 1", "words": ["tener", "artículo", "busco"]},
        {"title": "Asking for Specific Item – 2", "words": ["disponible", "tener", "producto"]},
        {"title": "Asking for Fresh – 1", "words": ["fresco", "hoy", "producto"]},
        {"title": "Asking for Fresh – 2", "words": ["maduro", "verde", "fruta"]},
        {"title": "Asking for Ripe – 1", "words": ["maduro", "listo", "comer"]},
        {"title": "Asking for Ripe – 2", "words": ["verde", "esperar", "madurar"]},
        {"title": "Asking for Organic – 1", "words": ["orgánico", "tener", "producto"]},
        {"title": "Asking for Organic – 2", "words": ["natural", "orgánico", "precio"]},
        # 21-30: Prices and payment
        {"title": "Asking Price – 1", "words": ["precio", "cuánto", "cuesta"]},
        {"title": "Asking Price – 2", "words": ["costo", "kilo", "precio"]},
        {"title": "On Sale – 1", "words": ["oferta", "rebaja", "precio"]},
        {"title": "On Sale – 2", "words": ["especial", "precio", "descuento"]},
        {"title": "Total Cost – 1", "words": ["total", "cuánto", "todo"]},
        {"title": "Total Cost – 2", "words": ["suma", "precio", "total"]},
        {"title": "Payment Method – 1", "words": ["pagar", "efectivo", "tarjeta"]},
        {"title": "Payment Method – 2", "words": ["tarjeta", "débito", "aceptar"]},
        {"title": "Change – 1", "words": ["cambio", "vuelto", "dinero"]},
        {"title": "Change – 2", "words": ["vuelto", "correcto", "verificar"]},
        # 31-40: Bags and packaging
        {"title": "Need a Bag – 1", "words": ["bolsa", "necesito", "plástico"]},
        {"title": "Need a Bag – 2", "words": ["saco", "bolsa", "llevar"]},
        {"title": "Reusable Bag – 1", "words": ["bolsa", "reutilizable", "tener"]},
        {"title": "Reusable Bag – 2", "words": ["ecológica", "bolsa", "traje"]},
        {"title": "Packaging – 1", "words": ["empaque", "envase", "producto"]},
        {"title": "Packaging – 2", "words": ["paquete", "abrir", "ver"]},
        {"title": "Receipt – 1", "words": ["recibo", "ticket", "necesito"]},
        {"title": "Receipt – 2", "words": ["factura", "recibo", "imprimir"]},
        {"title": "Grocery Cart – 1", "words": ["carrito", "dónde", "tomar"]},
        {"title": "Grocery Cart – 2", "words": ["carrito", "devolver", "dónde"]},
        # 41-50: Special requests
        {"title": "Cutting/Slicing – 1", "words": ["cortar", "rebanar", "queso"]},
        {"title": "Cutting/Slicing – 2", "words": ["filetear", "pescado", "cortar"]},
        {"title": "Weighing Items – 1", "words": ["pesar", "producto", "balanza"]},
        {"title": "Weighing Items – 2", "words": ["peso", "kilo", "verificar"]},
        {"title": "Store Hours – 1", "words": ["horario", "tienda", "abierto"]},
        {"title": "Store Hours – 2", "words": ["cerrar", "abrir", "horario"]},
        {"title": "Store Location – 1", "words": ["sucursal", "otra", "cerca"]},
        {"title": "Store Location – 2", "words": ["dirección", "tienda", "dónde"]},
        {"title": "Delivery Service – 1", "words": ["entrega", "domicilio", "servicio"]},
        {"title": "Delivery Service – 2", "words": ["llevar", "casa", "costo"]},
    ],
    
    "mechanic": [
        # 1-10: Car problems
        {"title": "Car Won't Start – 1", "words": ["carro", "no", "arranca"]},
        {"title": "Car Won't Start – 2", "words": ["motor", "problema", "arrancar"]},
        {"title": "Car Making Noise – 1", "words": ["ruido", "carro", "extraño"]},
        {"title": "Car Making Noise – 2", "words": ["sonido", "raro", "motor"]},
        {"title": "Brake Problem – 1", "words": ["freno", "problema", "no"]},
        {"title": "Brake Problem – 2", "words": ["frenar", "bien", "freno"]},
        {"title": "Engine Problem – 1", "words": ["motor", "problema", "reparar"]},
        {"title": "Engine Problem – 2", "words": ["motor", "temperatura", "caliente"]},
        {"title": "Battery Dead – 1", "words": ["batería", "muerta", "cargar"]},
        {"title": "Battery Dead – 2", "words": ["batería", "cambio", "nueva"]},
        # 11-20: Specific repairs
        {"title": "Oil Change – 1", "words": ["aceite", "cambiar", "motor"]},
        {"title": "Oil Change – 2", "words": ["cambio", "aceite", "cuándo"]},
        {"title": "Tire Problem – 1", "words": ["llanta", "pinchada", "cambiar"]},
        {"title": "Tire Problem – 2", "words": ["neumático", "desinflado", "aire"]},
        {"title": "Transmission – 1", "words": ["transmisión", "problema", "reparar"]},
        {"title": "Transmission – 2", "words": ["cambio", "marcha", "problema"]},
        {"title": "AC Not Working – 1", "words": ["aire", "acondicionado", "no"]},
        {"title": "AC Not Working – 2", "words": ["refrigerante", "aire", "recargar"]},
        {"title": "Lights Not Working – 1", "words": ["luz", "foco", "cambiar"]},
        {"title": "Lights Not Working – 2", "words": ["bombilla", "quemada", "nueva"]},
        # 21-30: Service and maintenance
        {"title": "Regular Service – 1", "words": ["servicio", "mantenimiento", "regular"]},
        {"title": "Regular Service – 2", "words": ["revisión", "carro", "general"]},
        {"title": "How Long – 1", "words": ["cuánto", "tiempo", "tardar"]},
        {"title": "How Long – 2", "words": ["horas", "días", "terminar"]},
        {"title": "How Much – 1", "words": ["cuánto", "cuesta", "reparar"]},
        {"title": "How Much – 2", "words": ["precio", "costo", "total"]},
        {"title": "When Ready – 1", "words": ["cuándo", "listo", "terminar"]},
        {"title": "When Ready – 2", "words": ["listo", "avisar", "llamar"]},
        {"title": "Warranty – 1", "words": ["garantía", "trabajo", "años"]},
        {"title": "Warranty – 2", "words": ["cubrir", "garantía", "problema"]},
        # 31-40: Parts and costs
        {"title": "Parts Needed – 1", "words": ["repuesto", "pieza", "necesario"]},
        {"title": "Parts Needed – 2", "words": ["parte", "cambiar", "nueva"]},
        {"title": "Parts Cost – 1", "words": ["costo", "repuesto", "cuánto"]},
        {"title": "Parts Cost – 2", "words": ["precio", "pieza", "incluido"]},
        {"title": "Original Parts – 1", "words": ["original", "repuesto", "genuino"]},
        {"title": "Original Parts – 2", "words": ["marca", "original", "alternativo"]},
        {"title": "Labor Cost – 1", "words": ["mano", "obra", "costo"]},
        {"title": "Labor Cost – 2", "words": ["trabajo", "hora", "precio"]},
        {"title": "Total Estimate – 1", "words": ["presupuesto", "total", "costo"]},
        {"title": "Total Estimate – 2", "words": ["estimado", "precio", "aproximado"]},
        # 41-50: Payment and pickup
        {"title": "Payment Method – 1", "words": ["pagar", "efectivo", "tarjeta"]},
        {"title": "Payment Method – 2", "words": ["tarjeta", "aceptar", "pago"]},
        {"title": "Payment Plan – 1", "words": ["pago", "cuotas", "posible"]},
        {"title": "Payment Plan – 2", "words": ["dividir", "pago", "meses"]},
        {"title": "Pick Up Car – 1", "words": ["recoger", "carro", "cuándo"]},
        {"title": "Pick Up Car – 2", "words": ["listo", "retirar", "hora"]},
        {"title": "Test Drive – 1", "words": ["probar", "carro", "conducir"]},
        {"title": "Test Drive – 2", "words": ["probar", "reparación", "funciona"]},
        {"title": "Receipt – 1", "words": ["recibo", "factura", "necesito"]},
        {"title": "Receipt – 2", "words": ["comprobante", "pago", "imprimir"]},
    ],
    
    "police": [
        # 1-10: Traffic stops
        {"title": "Traffic Stop – 1", "words": ["policía", "alto", "detener"]},
        {"title": "Traffic Stop – 2", "words": ["licencia", "documento", "mostrar"]},
        {"title": "Traffic Stop – 3", "words": ["velocidad", "límite", "exceder"]},
        {"title": "Traffic Stop – 4", "words": ["multa", "infracción", "razón"]},
        {"title": "Traffic Stop – 5", "words": ["señal", "alto", "no"]},
        {"title": "Traffic Stop – 6", "words": ["semáforo", "rojo", "pasar"]},
        {"title": "Traffic Stop – 7", "words": ["cinturón", "seguridad", "poner"]},
        {"title": "Traffic Stop – 8", "words": ["seguro", "vehículo", "tener"]},
        {"title": "Traffic Stop – 9", "words": ["registro", "vehículo", "mostrar"]},
        {"title": "Traffic Stop – 10", "words": ["alcohol", "prueba", "soplar"]},
        # 11-20: Document checks
        {"title": "Passport Check – 1", "words": ["pasaporte", "mostrar", "documento"]},
        {"title": "Passport Check – 2", "words": ["identificación", "documento", "tener"]},
        {"title": "Passport Check – 3", "words": ["visa", "permiso", "mostrar"]},
        {"title": "Passport Check – 4", "words": ["sello", "entrada", "pasaporte"]},
        {"title": "Address Verification – 1", "words": ["dirección", "dónde", "vives"]},
        {"title": "Address Verification – 2", "words": ["domicilio", "dirección", "actual"]},
        {"title": "Residency Status – 1", "words": ["residencia", "permiso", "tener"]},
        {"title": "Residency Status – 2", "words": ["estado", "migratorio", "documento"]},
        {"title": "Work Permit – 1", "words": ["permiso", "trabajo", "tener"]},
        {"title": "Work Permit – 2", "words": ["licencia", "trabajar", "válida"]},
        # 21-30: Fines and violations
        {"title": "Receiving a Fine – 1", "words": ["multa", "pagar", "cuánto"]},
        {"title": "Receiving a Fine – 2", "words": ["infracción", "costo", "multa"]},
        {"title": "Receiving a Fine – 3", "words": ["pagar", "dónde", "multa"]},
        {"title": "Receiving a Fine – 4", "words": ["plazo", "pagar", "días"]},
        {"title": "Appealing Fine – 1", "words": ["reclamar", "multa", "apelar"]},
        {"title": "Appealing Fine – 2", "words": ["discrepar", "multa", "razón"]},
        {"title": "Parking Ticket – 1", "words": ["multa", "estacionamiento", "pagar"]},
        {"title": "Parking Ticket – 2", "words": ["ticket", "estacionamiento", "multa"]},
        {"title": "Parking Ticket – 3", "words": ["zona", "prohibida", "estacionar"]},
        {"title": "Parking Ticket – 4", "words": ["permiso", "estacionar", "tener"]},
        # 31-40: Accidents and incidents
        {"title": "Car Accident – 1", "words": ["accidente", "choque", "reportar"]},
        {"title": "Car Accident – 2", "words": ["colisión", "vehículo", "daño"]},
        {"title": "Car Accident – 3", "words": ["seguro", "informe", "necesito"]},
        {"title": "Car Accident – 4", "words": ["responsable", "culpa", "quién"]},
        {"title": "Theft Report – 1", "words": ["robo", "reportar", "denuncia"]},
        {"title": "Theft Report – 2", "words": ["hurto", "artículo", "perdido"]},
        {"title": "Theft Report – 3", "words": ["denuncia", "policía", "hacer"]},
        {"title": "Theft Report – 4", "words": ["reporte", "caso", "número"]},
        {"title": "Lost Item – 1", "words": ["perdido", "artículo", "encontrar"]},
        {"title": "Lost Item – 2", "words": ["objeto", "perdido", "oficina"]},
        # 41-50: General police interactions
        {"title": "Asking Directions – 1", "words": ["dirección", "cómo", "llegar"]},
        {"title": "Asking Directions – 2", "words": ["dónde", "calle", "ubicar"]},
        {"title": "Reporting Crime – 1", "words": ["delito", "reportar", "denuncia"]},
        {"title": "Reporting Crime – 2", "words": ["crimen", "ocurrió", "cuándo"]},
        {"title": "Witness Statement – 1", "words": ["testigo", "declaración", "hacer"]},
        {"title": "Witness Statement – 2", "words": ["viste", "ocurrió", "qué"]},
        {"title": "Police Station – 1", "words": ["comisaría", "estación", "dónde"]},
        {"title": "Police Station – 2", "words": ["oficina", "policía", "dirección"]},
        {"title": "Emergency – 1", "words": ["emergencia", "ayuda", "necesito"]},
        {"title": "Emergency – 2", "words": ["urgencia", "llamar", "número"]},
    ],
    
    "restaurant": [
        # 1-10: Ordering food
        {"title": "Ordering Coffee – 1", "words": ["café", "pedir", "quiero"]},
        {"title": "Ordering Coffee – 2", "words": ["café", "leche", "azúcar"]},
        {"title": "Ordering Food – 1", "words": ["comida", "pedir", "menú"]},
        {"title": "Ordering Food – 2", "words": ["plato", "quiero", "ordenar"]},
        {"title": "Ordering Drinks – 1", "words": ["bebida", "agua", "pedir"]},
        {"title": "Ordering Drinks – 2", "words": ["refresco", "jugo", "bebida"]},
        {"title": "Asking About Menu – 1", "words": ["menú", "ver", "tener"]},
        {"title": "Asking About Menu – 2", "words": ["carta", "menú", "mostrar"]},
        {"title": "Special Request – 1", "words": ["especial", "pedido", "modificar"]},
        {"title": "Special Request – 2", "words": ["cambio", "plato", "hacer"]},
        # 11-20: Dietary restrictions
        {"title": "Diet Restriction – 1", "words": ["alergia", "tener", "alimento"]},
        {"title": "Diet Restriction – 2", "words": ["vegetariano", "vegano", "soy"]},
        {"title": "Diet Restriction – 3", "words": ["sin", "gluten", "lactosa"]},
        {"title": "Diet Restriction – 4", "words": ["no", "puedo", "comer"]},
        {"title": "Spicy Level – 1", "words": ["picante", "nivel", "qué"]},
        {"title": "Spicy Level – 2", "words": ["poco", "mucho", "picante"]},
        {"title": "Ingredients Question – 1", "words": ["ingrediente", "contiene", "qué"]},
        {"title": "Ingredients Question – 2", "words": ["tiene", "carne", "pescado"]},
        {"title": "Portion Size – 1", "words": ["porción", "tamaño", "grande"]},
        {"title": "Portion Size – 2", "words": ["racion", "suficiente", "compartir"]},
        # 21-30: During the meal
        {"title": "Need Something – 1", "words": ["necesito", "agua", "servilleta"]},
        {"title": "Need Something – 2", "words": ["traer", "cuchillo", "tenedor"]},
        {"title": "Food Not Right – 1", "words": ["plato", "mal", "cocido"]},
        {"title": "Food Not Right – 2", "words": ["frío", "caliente", "temperatura"]},
        {"title": "Food Too Salty – 1", "words": ["salado", "mucho", "sabor"]},
        {"title": "Food Too Spicy – 1", "words": ["picante", "mucho", "agua"]},
        {"title": "Compliment Food – 1", "words": ["rico", "delicioso", "comida"]},
        {"title": "Compliment Food – 2", "words": ["bueno", "gusta", "plato"]},
        {"title": "More Food – 1", "words": ["más", "comida", "porción"]},
        {"title": "More Food – 2", "words": ["repetir", "plato", "mismo"]},
        # 31-40: Payment
        {"title": "Asking for Bill – 1", "words": ["cuenta", "factura", "traer"]},
        {"title": "Asking for Bill – 2", "words": ["pagar", "cuenta", "por"]},
        {"title": "Splitting the Bill – 1", "words": ["dividir", "cuenta", "separar"]},
        {"title": "Splitting the Bill – 2", "words": ["pagar", "parte", "cuenta"]},
        {"title": "Payment Method – 1", "words": ["pagar", "tarjeta", "efectivo"]},
        {"title": "Payment Method – 2", "words": ["tarjeta", "aceptar", "pago"]},
        {"title": "Tip – 1", "words": ["propina", "incluida", "cuenta"]},
        {"title": "Tip – 2", "words": ["propina", "dejar", "cuánto"]},
        {"title": "Change – 1", "words": ["cambio", "vuelto", "correcto"]},
        {"title": "Change – 2", "words": ["vuelto", "verificar", "cuenta"]},
        # 41-50: Special situations
        {"title": "Reservation – 1", "words": ["reserva", "mesa", "tener"]},
        {"title": "Reservation – 2", "words": ["reservar", "mesa", "personas"]},
        {"title": "Wait Time – 1", "words": ["espera", "mesa", "cuánto"]},
        {"title": "Wait Time – 2", "words": ["tiempo", "esperar", "minutos"]},
        {"title": "Table Request – 1", "words": ["mesa", "ventana", "preferir"]},
        {"title": "Table Request – 2", "words": ["mesa", "fumadores", "no"]},
        {"title": "Take Out – 1", "words": ["para", "llevar", "comida"]},
        {"title": "Take Out – 2", "words": ["llevar", "domicilio", "envase"]},
        {"title": "Restroom – 1", "words": ["baño", "dónde", "ubicado"]},
        {"title": "Restroom – 2", "words": ["servicio", "aseo", "dirección"]},
    ],
}

