"""
Add all 1000 high-frequency words from Wiktionary list.
Excludes standalone grammar words (la, el, lo, un, una, los, las, me, te, le, se, nos, os)
but includes them in phrases (del, al, porque, etc.)
"""
import sys
import os
from pathlib import Path

env_path = Path(__file__).parent.parent / '.env'
if env_path.exists():
    from dotenv import load_dotenv
    load_dotenv(env_path)

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

from sqlalchemy.orm import Session
from app.database import SessionLocal
from app.models import Word

# Grammar words to exclude as standalone (but include in phrases)
EXCLUDED_STANDALONE = {"la", "el", "lo", "un", "una", "los", "las", "me", "te", "le", "se", "nos", "os"}

# All 1000 words from Wiktionary - format: (rank, spanish, english)
ALL_1000_WORDS = [
    (1, "que", "that, which, what"),
    (2, "de", "of, from"),
    (3, "no", "no, not"),
    (4, "a", "to, at"),
    # (5, "la", "the (feminine)"),  # EXCLUDED
    # (6, "el", "the (masculine)"),  # EXCLUDED
    (7, "es", "is"),
    (8, "y", "and"),
    (9, "en", "in, on"),
    # (10, "lo", "it, the"),  # EXCLUDED
    # (11, "un", "a, an (masculine)"),  # EXCLUDED
    (12, "por", "for, by, through"),
    (13, "qué", "what"),
    # (14, "me", "me"),  # EXCLUDED
    # (15, "una", "a, an (feminine)"),  # EXCLUDED
    # (16, "te", "you (informal)"),  # EXCLUDED
    # (17, "los", "the (masculine plural)"),  # EXCLUDED
    # (18, "se", "oneself, itself"),  # EXCLUDED
    (19, "con", "with"),
    (20, "para", "for, to"),
    (21, "mi", "my"),
    (22, "está", "is (location/state)"),
    (23, "si", "if"),
    (24, "bien", "well, good"),
    (25, "pero", "but"),
    (26, "yo", "I"),
    (27, "eso", "that"),
    # (28, "las", "the (feminine plural)"),  # EXCLUDED
    (29, "sí", "yes"),
    (30, "su", "his, her, your, their"),
    (31, "tu", "your (informal)"),
    (32, "aquí", "here"),
    (33, "del", "of the, from the"),  # KEPT: phrase
    (34, "al", "to the"),  # KEPT: phrase
    (35, "como", "like, as, how"),
    # (36, "le", "him, her, you (formal)"),  # EXCLUDED
    (37, "más", "more"),
    (38, "esto", "this"),
    (39, "ya", "already, now"),
    (40, "todo", "all, everything"),
    (41, "esta", "this (feminine)"),
    (42, "vamos", "let's go"),
    (43, "muy", "very"),
    (44, "hay", "there is/are"),
    (45, "ahora", "now"),
    (46, "algo", "something"),
    (47, "estoy", "I am"),
    (48, "tengo", "I have"),
    # (49, "nos", "us"),  # EXCLUDED
    (50, "tú", "you (informal)"),
    (51, "nada", "nothing"),
    (52, "cuando", "when"),
    (53, "ha", "has"),
    (54, "este", "this (masculine)"),
    (55, "sé", "I know"),
    (56, "estás", "you are"),
    (57, "así", "like this, so"),
    (58, "puedo", "I can"),
    (59, "cómo", "how"),
    (60, "quiero", "I want"),
    (61, "sólo", "only"),
    (62, "soy", "I am"),
    (63, "tiene", "has"),
    (64, "gracias", "thanks"),
    (65, "o", "or"),
    (66, "él", "he"),
    (67, "bueno", "good"),
    (68, "fue", "was, went"),
    (69, "ser", "to be (permanent)"),
    (70, "hacer", "to do, to make"),
    (71, "son", "they are"),
    (72, "todos", "all, everyone"),
    (73, "era", "was, used to be"),
    (74, "eres", "you are"),
    (75, "vez", "time, turn"),
    (76, "tienes", "you have"),
    (77, "creo", "I believe"),
    (78, "ella", "she"),
    (79, "he", "I have"),
    (80, "ese", "that (masculine)"),
    (81, "voy", "I go"),
    (82, "puede", "can, may"),
    (83, "sabes", "you know"),
    (84, "hola", "hello"),
    (85, "sus", "their, your (plural)"),
    (86, "porque", "because"),  # KEPT: phrase
    (87, "dios", "god"),
    (88, "quién", "who"),
    (89, "nunca", "never"),
    (90, "dónde", "where"),
    (91, "quieres", "you want"),
    (92, "casa", "house"),
    (93, "favor", "favor"),
    (94, "esa", "that (feminine)"),
    (95, "dos", "two"),
    (96, "tan", "so, as"),
    (97, "señor", "sir, mister"),
    (98, "tiempo", "time, weather"),
    (99, "verdad", "truth"),
    (100, "estaba", "was (location/state)"),
    (101, "mejor", "better, best"),
    (102, "están", "they are"),
    (103, "va", "goes"),
    (104, "hombre", "man"),
    (105, "usted", "you (formal)"),
    (106, "mucho", "much, many"),
    (107, "hace", "does, makes"),
    (108, "entonces", "then"),
    (109, "siento", "I feel, I'm sorry"),
    (110, "tenemos", "we have"),
    (111, "puedes", "you can"),
    (112, "ahí", "there"),
    (113, "ti", "you (object)"),
    (114, "vida", "life"),
    (115, "ver", "to see"),
    (116, "alguien", "someone"),
    (117, "sr", "sir, mister (abbrev)"),
    (118, "hasta", "until, even"),
    (119, "sin", "without"),
    (120, "mí", "me (object)"),
    (121, "solo", "alone, only"),
    (122, "años", "years"),
    (123, "sobre", "on, about"),
    (124, "decir", "to say, to tell"),
    (125, "uno", "one"),
    (126, "siempre", "always"),
    (127, "oh", "oh"),
    (128, "ir", "to go"),
    (129, "cosas", "things"),
    (130, "también", "also, too"),
    (131, "antes", "before"),
    (132, "has", "you have"),
    (133, "ni", "neither, nor"),
    (134, "mis", "my (plural)"),
    (135, "día", "day"),
    (136, "estar", "to be (location/state)"),
    (137, "estamos", "we are"),
    (138, "noche", "night"),
    (139, "nadie", "nobody"),
    (140, "otra", "other, another (feminine)"),
    (141, "quiere", "wants"),
    (142, "parece", "seems"),
    (143, "nosotros", "we"),
    (144, "poco", "little, few"),
    (145, "padre", "father"),
    (146, "trabajo", "work, job"),
    (147, "gente", "people"),
    (148, "mira", "look"),
    (149, "vas", "you go"),
    (150, "sea", "be (subjunctive)"),
    (151, "les", "them, you (plural object)"),
    (152, "donde", "where"),
    (153, "mismo", "same"),
    (154, "hecho", "done, fact"),
    (155, "ellos", "they (masculine)"),
    (156, "dijo", "said"),
    (157, "pasa", "happens, passes"),
    (158, "dinero", "money"),
    (159, "hijo", "son"),
    (160, "tal", "such"),
    (161, "otro", "other, another (masculine)"),
    (162, "hablar", "to speak"),
    (163, "seguro", "sure, safe"),
    (164, "claro", "clear, of course"),
    (165, "estas", "these (feminine)"),
    (166, "lugar", "place"),
    (167, "mundo", "world"),
    (168, "amigo", "friend (masculine)"),
    (169, "espera", "wait"),
    (170, "mierda", "shit"),
    (171, "han", "they have"),
    (172, "tus", "your (plural)"),
    (173, "sabe", "knows"),
    (174, "después", "after, later"),
    (175, "momento", "moment"),
    (176, "desde", "since, from"),
    (177, "fuera", "outside"),
    (178, "cosa", "thing"),
    (179, "tipo", "type, guy"),
    (180, "mañana", "morning, tomorrow"),
    (181, "podemos", "we can"),
    (182, "dije", "I said"),
    (183, "gran", "great, large"),
    (184, "necesito", "I need"),
    (185, "estado", "state, been"),
    (186, "podría", "could"),
    (187, "acuerdo", "agreement"),
    (188, "papá", "dad"),
    (189, "tener", "to have"),
    (190, "dice", "says"),
    (191, "mío", "mine"),
    (192, "crees", "you believe"),
    (193, "buena", "good (feminine)"),
    (194, "gusta", "likes"),
    (195, "nuestro", "our (masculine)"),
    (196, "nuevo", "new"),
    (197, "será", "will be"),
    (198, "haciendo", "doing"),
    (199, "días", "days"),
    (200, "nombre", "name"),
    (201, "buen", "good (before noun)"),
    (202, "había", "there was/were"),
    (203, "ven", "come"),
    (204, "tres", "three"),
    (205, "menos", "less"),
    (206, "debe", "must, owes"),
    (207, "tenía", "had"),
    (208, "mal", "bad, badly"),
    (209, "conmigo", "with me"),
    (210, "madre", "mother"),
    (211, "hoy", "today"),
    (212, "quien", "who"),
    (213, "sido", "been"),
    (214, "mamá", "mom"),
    (215, "tienen", "they have"),
    (216, "luego", "then, later"),
    (217, "todas", "all (feminine plural)"),
    (218, "allí", "there"),
    (219, "toda", "all (feminine)"),
    (220, "hora", "hour, time"),
    (221, "mujer", "woman"),
    (222, "visto", "seen"),
    (223, "haces", "you do"),
    (224, "importa", "matters"),
    (225, "contigo", "with you"),
    (226, "ve", "see, go"),
    (227, "tarde", "late, afternoon"),
    (228, "oye", "hear, hey"),
    (229, "parte", "part"),
    (230, "haber", "to have (auxiliary)"),
    (231, "hombres", "men"),
    (232, "problema", "problem"),
    (233, "mas", "but (formal)"),
    (234, "saber", "to know"),
    (235, "quería", "wanted"),
    (236, "aún", "still, yet"),
    (237, "veces", "times"),
    (238, "nuestra", "our (feminine)"),
    (239, "hacerlo", "to do it"),
    (240, "cada", "each, every"),
    (241, "hizo", "did, made"),
    (242, "veo", "I see"),
    (243, "tanto", "so much"),
    (244, "razón", "reason"),
    (245, "ustedes", "you (plural)"),
    (246, "idea", "idea"),
    (247, "esos", "those (masculine)"),
    (248, "van", "they go"),
    (249, "quizá", "maybe"),
    (250, "debo", "I must"),
    (251, "alguna", "some (feminine)"),
    (252, "cierto", "certain, sure"),
    (253, "ud", "you (formal, abbrev)"),
    (254, "muerto", "dead"),
    (255, "unos", "some (masculine plural)"),
    (256, "estos", "these (masculine)"),
    (257, "salir", "to leave, to go out"),
    (258, "policía", "police, police officer"),
    (259, "realmente", "really"),
    (260, "demasiado", "too much"),
    (261, "familia", "family"),
    (262, "pueden", "they can"),
    (263, "cabeza", "head"),
    (264, "hemos", "we have"),
    (265, "amigos", "friends"),
    (266, "chica", "girl"),
    (267, "cariño", "dear, affection"),
    (268, "lado", "side"),
    (269, "allá", "there (far)"),
    (270, "entre", "between, among"),
    (271, "minutos", "minutes"),
    (272, "digo", "I say"),
    (273, "algún", "some (masculine)"),
    (274, "serio", "serious"),
    (275, "cuidado", "care, careful"),
    (276, "pasó", "happened, passed"),
    (277, "buenas", "good (feminine plural)"),
    (278, "somos", "we are"),
    (279, "amor", "love"),
    (280, "puerta", "door"),
    (281, "ves", "you see"),
    (282, "vaya", "go (subjunctive), wow"),
    (283, "ah", "ah"),
    (284, "suerte", "luck"),
    (285, "eh", "eh"),
    (286, "rápido", "fast"),
    (287, "cuenta", "account, bill"),
    (288, "quizás", "maybe"),
    (289, "esas", "those (feminine)"),
    (290, "pues", "well, then"),
    (291, "pasado", "past, passed"),
    (292, "pensé", "I thought"),
    (293, "todavía", "still"),
    (294, "hermano", "brother"),
    (295, "debes", "you must"),
    (296, "casi", "almost"),
    (297, "forma", "form, way"),
    (298, "aqui", "here (misspelling)"),
    (299, "chico", "boy, guy"),
    (300, "ok", "okay"),
    (301, "dicho", "said"),
    (302, "nueva", "new (feminine)"),
    (303, "sabía", "knew"),
    (304, "muchas", "many (feminine)"),
    (305, "dentro", "inside"),
    (306, "hice", "I did"),
    (307, "contra", "against"),
    (308, "auto", "car"),
    (309, "camino", "road, way"),
    (310, "ayuda", "help"),
    (311, "primera", "first (feminine)"),
    (312, "hacia", "toward"),
    (313, "vi", "I saw"),
    (314, "miedo", "fear"),
    (315, "adiós", "goodbye"),
    (316, "primero", "first"),
    (317, "debería", "should"),
    (318, "poder", "to be able to"),
    (319, "niños", "children, boys"),
    (320, "sería", "would be"),
    (321, "historia", "history, story"),
    (322, "hey", "hey"),
    (323, "mientras", "while"),
    (324, "ciudad", "city"),
    (325, "dijiste", "you said"),
    (326, "espero", "I hope, I wait"),
    (327, "cuánto", "how much"),
    (328, "esposa", "wife"),
    (329, "pronto", "soon"),
    (330, "chicos", "boys, guys"),
    (331, "cualquier", "any"),
    (332, "viejo", "old"),
    (333, "debemos", "we must"),
    (334, "deja", "leave, let"),
    (335, "año", "year"),
    (336, "muerte", "death"),
    (337, "hablando", "speaking"),
    (338, "manos", "hands"),
    (339, "da", "gives"),
    (340, "loco", "crazy"),
    (341, "problemas", "problems"),
    (342, "mano", "hand"),
    (343, "guerra", "war"),
    (344, "semana", "week"),
    (345, "pasar", "to pass, to happen"),
    (346, "vale", "okay, worth"),
    (347, "cuál", "which"),
    (348, "viene", "comes"),
    (349, "volver", "to return"),
    (350, "toma", "take"),
    (351, "caso", "case"),
    (352, "agua", "water"),
    (353, "haré", "I will do"),
    (354, "vete", "go away"),
    (355, "entiendo", "I understand"),
    (356, "horas", "hours"),
    (357, "personas", "people"),
    (358, "capitán", "captain"),
    (359, "adelante", "forward, ahead"),
    (360, "niño", "child, boy"),
    (361, "listo", "ready"),
    (362, "noches", "nights"),
    (363, "buenos", "good (masculine plural)"),
    (364, "iba", "was going"),
    (365, "juntos", "together"),
    (366, "dame", "give me"),
    (367, "único", "unique, only"),
    (368, "déjame", "let me"),
    (369, "cerca", "near, close"),
    (370, "otros", "others"),
    (371, "sigue", "follows, continues"),
    (372, "grande", "big, large"),
    (373, "arriba", "up, above"),
    (374, "jefe", "boss"),
    (375, "habla", "speaks, speech"),
    (376, "supongo", "I suppose"),
    (377, "manera", "way, manner"),
    (378, "quieren", "they want"),
    (379, "feliz", "happy"),
    (380, "significa", "means"),
    (381, "sangre", "blood"),
    (382, "fin", "end"),
    (383, "bajo", "low, under"),
    (384, "llama", "calls, flame"),
    (385, "venir", "to come"),
    (386, "morir", "to die"),
    (387, "importante", "important"),
    (388, "hiciste", "you did"),
    (389, "ojos", "eyes"),
    (390, "escucha", "listen"),
    (391, "entrar", "to enter"),
    (392, "ningún", "no, none (masculine)"),
    (393, "corazón", "heart"),
    (394, "diablos", "devils"),
    (395, "necesitamos", "we need"),
    (396, "atrás", "behind, back"),
    (397, "durante", "during"),
    (398, "dices", "you say"),
    (399, "nuestros", "our (masculine plural)"),
    (400, "persona", "person"),
    (401, "abajo", "down, below"),
    (402, "dr", "doctor (abbrev)"),
    (403, "hija", "daughter"),
    (404, "dejar", "to leave, to let"),
    (405, "necesita", "needs"),
    (406, "llegar", "to arrive"),
    (407, "hago", "I do"),
    (408, "señora", "madam, Mrs."),
    (409, "haya", "there is (subjunctive)"),
    (410, "suficiente", "enough"),
    (411, "doctor", "doctor"),
    (412, "gustaría", "would like"),
    (413, "tierra", "earth, land"),
    (414, "cara", "face"),
    (415, "siquiera", "at least"),
    (416, "genial", "great, genius"),
    (417, "cree", "believes"),
    (418, "supuesto", "supposed"),
    (419, "tomar", "to take"),
    (420, "equipo", "team, equipment"),
    (421, "justo", "just, fair"),
    (422, "juego", "game"),
    (423, "ninguna", "no, none (feminine)"),
    (424, "matar", "to kill"),
    (425, "cinco", "five"),
    (426, "dicen", "they say"),
    (427, "amo", "I love, master"),
    (428, "cuándo", "when"),
    (429, "pequeño", "small"),
    (430, "algunos", "some (masculine plural)"),
    (431, "conozco", "I know (person)"),
    (432, "clase", "class"),
    (433, "maldito", "damned"),
    (434, "unas", "some (feminine plural)"),
    (435, "muchos", "many (masculine)"),
    (436, "hubiera", "had (subjunctive)"),
    (437, "segundo", "second"),
    (438, "aunque", "although"),
    (439, "pueda", "can (subjunctive)"),
    (440, "dime", "tell me"),
    (441, "igual", "equal, same"),
    (442, "comida", "food"),
    (443, "ay", "oh"),
    (444, "cuerpo", "body"),
    (445, "encontrar", "to find"),
    (446, "fuerte", "strong"),
    (447, "vuelta", "turn, return"),
    (448, "venga", "come (subjunctive)"),
    (449, "creer", "to believe"),
    (450, "realidad", "reality"),
    (451, "saben", "they know"),
    (452, "puta", "whore"),
    (453, "deberías", "you should"),
    (454, "pregunta", "question"),
    (455, "fui", "I went, I was"),
    (456, "cuatro", "four"),
    (457, "sra", "Mrs. (abbrev)"),
    (458, "primer", "first (before noun)"),
    (459, "trabajar", "to work"),
    (460, "e", "and (before i/hi)"),
    (461, "hagas", "you do (subjunctive)"),
    (462, "alto", "tall, high"),
    (463, "maldita", "damned (feminine)"),
    (464, "comer", "to eat"),
    (465, "número", "number"),
    (466, "dar", "to give"),
    (467, "necesitas", "you need"),
    (468, "oportunidad", "opportunity"),
    (469, "punto", "point, dot"),
    (470, "misma", "same (feminine)"),
    (471, "última", "last (feminine)"),
    (472, "afuera", "outside"),
    (473, "mujeres", "women"),
    (474, "pensar", "to think"),
    (475, "fueron", "they went, they were"),
    (476, "difícil", "difficult"),
    (477, "vivir", "to live"),
    (478, "paso", "step, pass"),
    (479, "malo", "bad"),
    (480, "estabas", "you were"),
    (481, "vivo", "alive, I live"),
    (482, "haga", "do (subjunctive)"),
    (483, "queda", "remains, stays"),
    (484, "hijos", "sons, children"),
    (485, "mayor", "older, major"),
    (486, "fiesta", "party"),
    (487, "hacen", "they do"),
    (488, "medio", "half, medium"),
    (489, "algunas", "some (feminine plural)"),
    (490, "basta", "enough"),
    (491, "arma", "weapon"),
    (492, "vino", "wine, came"),
    (493, "meses", "months"),
    (494, "cuarto", "fourth, room"),
    (495, "éste", "this one"),
    (496, "escuela", "school"),
    (497, "esté", "be (subjunctive)"),
    (498, "dólares", "dollars"),
    (499, "tío", "uncle"),
    (500, "posible", "possible"),
    (501, "tuve", "I had"),
    (502, "fácil", "easy"),
    (503, "preocupes", "worry (subjunctive)"),
    (504, "luz", "light"),
    (505, "eran", "they were"),
    (506, "carajo", "damn"),
    (507, "final", "final"),
    (508, "lista", "list, ready (feminine)"),
    (509, "trata", "treats, deals"),
    (510, "armas", "weapons"),
    (511, "hermana", "sister"),
    (512, "exactamente", "exactly"),
    (513, "chicas", "girls"),
    (514, "podía", "could"),
    (515, "bastante", "quite, enough"),
    (516, "seguridad", "security"),
    (517, "pasando", "passing, happening"),
    (518, "esperando", "waiting"),
    (519, "acá", "here"),
    (520, "teléfono", "telephone"),
    (521, "perro", "dog"),
    (522, "fuego", "fire"),
    (523, "murió", "died"),
    (524, "tampoco", "neither"),
    (525, "sola", "alone (feminine)"),
    (526, "estuvo", "was"),
    (527, "verte", "to see you"),
    (528, "iré", "I will go"),
    (529, "tenido", "had"),
    (530, "culpa", "fault, blame"),
    (531, "veras", "really"),
    (532, "adónde", "where to"),
    (533, "buscando", "looking for"),
    (534, "cuanto", "as much as"),
    (535, "padres", "parents"),
    (536, "paz", "peace"),
    (537, "demonios", "demons"),
    (538, "estará", "will be"),
    (539, "cual", "which"),
    (540, "perdón", "sorry, pardon"),
    (541, "asi", "like this (misspelling)"),
    (542, "jugar", "to play"),
    (543, "pensando", "thinking"),
    (544, "esperar", "to wait, to hope"),
    (545, "sabemos", "we know"),
    (546, "recuerdo", "memory, I remember"),
    (547, "par", "pair, even"),
    (548, "joven", "young"),
    (549, "seguir", "to follow, to continue"),
    (550, "pueblo", "town, people"),
    (551, "tenga", "have (subjunctive)"),
    (552, "caballeros", "gentlemen"),
    (553, "idiota", "idiot"),
    (554, "dio", "gave"),
    (555, "minuto", "minute"),
    (556, "bebé", "baby"),
    (557, "única", "unique, only (feminine)"),
    (558, "lejos", "far"),
    (559, "nuestras", "our (feminine plural)"),
    (560, "plan", "plan"),
    (561, "pienso", "I think"),
    (562, "sentido", "sense, felt"),
    (563, "dormir", "to sleep"),
    (564, "digas", "you say (subjunctive)"),
    (565, "palabra", "word"),
    (566, "correcto", "correct"),
    (567, "control", "control"),
    (568, "vemos", "we see"),
    (569, "entiendes", "you understand"),
    (570, "país", "country"),
    (571, "seis", "six"),
    (572, "último", "last"),
    (573, "ésta", "this one (feminine)"),
    (574, "diga", "say (subjunctive)"),
    (575, "podrías", "you could"),
    (576, "pequeña", "small (feminine)"),
    (577, "cállate", "shut up"),
    (578, "trato", "deal, treatment"),
    (579, "rey", "king"),
    (580, "sucede", "happens"),
    (581, "muchachos", "boys, guys"),
    (582, "jamás", "never"),
    (583, "cama", "bed"),
    (584, "srta", "Miss (abbrev)"),
    (585, "ayudar", "to help"),
    (586, "acerca", "about"),
    (587, "di", "give (command)"),
    (588, "cambio", "change"),
    (589, "falta", "lack, missing"),
    (590, "hospital", "hospital"),
    (591, "lleva", "carries, takes"),
    (592, "presidente", "president"),
    (593, "mil", "thousand"),
    (594, "gusto", "pleasure, taste"),
    (595, "conoces", "you know (person)"),
    (596, "diciendo", "saying"),
    # (597, "os", "you (plural object)"),  # EXCLUDED
    (598, "ido", "gone"),
    (599, "general", "general"),
    (600, "extraño", "strange, I miss"),
    (601, "semanas", "weeks"),
    (602, "coche", "car (Spain)"),
    (603, "peor", "worse"),
    (604, "mucha", "much (feminine)"),
    (605, "disculpe", "excuse me"),
    (606, "diré", "I will say"),
    (607, "anoche", "last night"),
    (608, "perder", "to lose"),
    (609, "vámonos", "let's go"),
    (610, "nave", "ship"),
    (611, "cielo", "sky, heaven"),
    (612, "habrá", "there will be"),
    (613, "orden", "order"),
    (614, "segura", "sure (feminine)"),
    (615, "querida", "dear (feminine)"),
    (616, "niña", "girl"),
    (617, "increíble", "incredible"),
    (618, "además", "besides"),
    (619, "deben", "they must"),
    (620, "libro", "book"),
    (621, "calle", "street"),
    (622, "café", "coffee"),
    (623, "piensas", "you think"),
    (624, "hacemos", "we do"),
    (625, "especial", "special"),
    (626, "queremos", "we want"),
    (627, "irme", "to leave"),
    (628, "perfecto", "perfect"),
    (629, "buscar", "to look for"),
    (630, "odio", "I hate, hatred"),
    (631, "piensa", "thinks"),
    (632, "oficina", "office"),
    (633, "hablas", "you speak"),
    (634, "libre", "free"),
    (635, "agente", "agent"),
    (636, "york", "York"),
    (637, "llamar", "to call"),
    (638, "mala", "bad (feminine)"),
    (639, "detrás", "behind"),
    (640, "viste", "you saw"),
    (641, "dile", "tell him/her"),
    (642, "grandes", "big (plural)"),
    (643, "recuerdas", "you remember"),
    (644, "real", "real"),
    (645, "estaban", "they were"),
    (646, "mía", "mine (feminine)"),
    (647, "frente", "front"),
    (648, "perdido", "lost"),
    (649, "llamo", "I call"),
    (650, "muertos", "dead (plural)"),
    (651, "millones", "millions"),
    (652, "asesino", "killer"),
    (653, "sueño", "dream, sleep"),
    (654, "quisiera", "I would like"),
    (655, "habría", "there would be"),
    (656, "hará", "will do"),
    (657, "viaje", "trip"),
    (658, "probablemente", "probably"),
    (659, "resto", "rest"),
    (660, "estaré", "I will be"),
    (661, "maldición", "curse"),
    (662, "lamento", "I'm sorry"),
    (663, "muchacho", "boy"),
    (664, "avión", "airplane"),
    (665, "ropa", "clothes"),
    (666, "fuerza", "force, strength"),
    (667, "llamado", "called"),
    (668, "oído", "heard, ear"),
    (669, "dado", "given, die"),
    (670, "encima", "on top"),
    (671, "negro", "black"),
    (672, "usar", "to use"),
    (673, "información", "information"),
    (674, "uds", "you (plural, abbrev)"),
    (675, "preguntas", "questions"),
    (676, "tuvo", "had"),
    (677, "secreto", "secret"),
    (678, "vuelve", "returns"),
    (679, "miren", "look (plural)"),
    (680, "quieras", "you want (subjunctive)"),
    (681, "haría", "would do"),
    (682, "acaba", "ends, finishes"),
    (683, "otras", "others (feminine)"),
    (684, "incluso", "even"),
    (685, "sientes", "you feel"),
    (686, "deberíamos", "we should"),
    (687, "haz", "do (command)"),
    (688, "decirte", "to tell you"),
    (689, "boca", "mouth"),
    (690, "dolor", "pain"),
    (691, "baño", "bathroom"),
    (692, "adentro", "inside"),
    (693, "profesor", "teacher"),
    (694, "habitación", "room"),
    (695, "daño", "damage"),
    (696, "tuyo", "yours"),
    (697, "seas", "be (subjunctive)"),
    (698, "noticias", "news"),
    (699, "demás", "others, rest"),
    (700, "querido", "dear (masculine)"),
    (701, "duro", "hard"),
    (702, "poner", "to put"),
    (703, "prueba", "test, proof"),
    (704, "mire", "look (formal)"),
    (705, "tonto", "fool"),
    (706, "campo", "field"),
    (707, "siendo", "being"),
    (708, "diez", "ten"),
    (709, "ése", "that one"),
    (710, "tranquilo", "calm"),
    (711, "asunto", "matter"),
    (712, "acabó", "ended"),
    (713, "quédate", "stay"),
    (714, "derecho", "right, straight"),
    (715, "placer", "pleasure"),
    (716, "recuerda", "remember"),
    (717, "estuve", "I was"),
    (718, "tratando", "trying"),
    (719, "ejército", "army"),
    (720, "futuro", "future"),
    (721, "llevar", "to carry, to take"),
    (722, "compañía", "company"),
    (723, "venido", "come"),
    (724, "listos", "ready (plural)"),
    (725, "haremos", "we will do"),
    (726, "sitio", "site, place"),
    (727, "verlo", "to see it"),
    (728, "puesto", "put, position"),
    (729, "atención", "attention"),
    (730, "sino", "but rather"),
    (731, "cambiar", "to change"),
    (732, "error", "error"),
    (733, "blanco", "white"),
    (734, "raro", "strange"),
    (735, "palabras", "words"),
    (736, "llegó", "arrived"),
    (737, "sal", "salt, go out (command)"),
    (738, "pase", "pass (subjunctive)"),
    (739, "mente", "mind"),
    (740, "sistema", "system"),
    (741, "película", "movie"),
    (742, "anda", "goes, walk"),
    (743, "ello", "it"),
    (744, "negocio", "business"),
    (745, "novia", "girlfriend"),
    (746, "permiso", "permission"),
    (747, "creí", "I believed"),
    (748, "suena", "sounds"),
    (749, "ocurre", "occurs"),
    (750, "oficial", "official"),
    (751, "espere", "wait (formal)"),
    (752, "aire", "air"),
    (753, "mató", "killed"),
    (754, "regresar", "to return"),
    (755, "vio", "saw"),
    (756, "hazlo", "do it"),
    (757, "trasero", "rear, behind"),
    (758, "grupo", "group"),
    (759, "entendido", "understood"),
    (760, "señorita", "miss"),
    (761, "música", "music"),
    (762, "perra", "bitch, female dog"),
    (763, "conoce", "knows (person)"),
    (764, "empezar", "to begin"),
    (765, "siente", "feels"),
    (766, "acabo", "I finish"),
    (767, "estúpido", "stupid"),
    (768, "diferente", "different"),
    (769, "traje", "brought, suit"),
    (770, "modo", "way, mode"),
    (771, "encontré", "I found"),
    (772, "mensaje", "message"),
    (773, "llamada", "call"),
    (774, "navidad", "Christmas"),
    (775, "eras", "you were"),
    (776, "pena", "shame, pity"),
    (777, "largo", "long"),
    (778, "entra", "enters"),
    (779, "piso", "floor, apartment"),
    (780, "foto", "photo"),
    (781, "dijeron", "they said"),
    (782, "médico", "doctor"),
    (783, "accidente", "accident"),
    (784, "fuiste", "you went, you were"),
    (785, "imposible", "impossible"),
    (786, "podríamos", "we could"),
    (787, "línea", "line"),
    (788, "propia", "own (feminine)"),
    (789, "barco", "ship"),
    (790, "ganar", "to win, to earn"),
    (791, "normal", "normal"),
    (792, "segundos", "seconds"),
    (793, "vive", "lives"),
    (794, "mitad", "half"),
    (795, "quiera", "want (subjunctive)"),
    (796, "tras", "after, behind"),
    (797, "decirle", "to tell him/her"),
    (798, "lindo", "pretty"),
    (799, "funciona", "works"),
    (800, "programa", "program"),
    (801, "vine", "I came"),
    (802, "abre", "opens"),
    (803, "sean", "be (subjunctive plural)"),
    (804, "pagar", "to pay"),
    (805, "fotos", "photos"),
    (806, "centro", "center"),
    (807, "supone", "supposes"),
    (808, "basura", "trash"),
    (809, "situación", "situation"),
    (810, "mejores", "best (plural)"),
    (811, "vienen", "they come"),
    (812, "encanta", "loves, enchants"),
    (813, "marido", "husband"),
    (814, "personal", "personal, staff"),
    (815, "maestro", "teacher, master"),
    (816, "hambre", "hunger"),
    (817, "ataque", "attack"),
    (818, "culo", "ass"),
    (819, "dale", "give (command)"),
    (820, "pie", "foot"),
    (821, "conseguir", "to get, to achieve"),
    (822, "trabajando", "working"),
    (823, "gracioso", "funny"),
    (824, "dejó", "left"),
    (825, "pudo", "could"),
    (826, "derecha", "right (direction)"),
    (827, "izquierda", "left"),
    (828, "próxima", "next (feminine)"),
    (829, "pobre", "poor"),
    (830, "respuesta", "answer"),
    (831, "tipos", "types, guys"),
    (832, "sentir", "to feel"),
    (833, "tenías", "you had"),
    (834, "pude", "I could"),
    (835, "darle", "to give him/her"),
    (836, "voz", "voice"),
    (837, "amiga", "friend (feminine)"),
    (838, "gustan", "they like"),
    (839, "vista", "view, sight"),
    (840, "salvo", "except, safe"),
    (841, "loca", "crazy (feminine)"),
    (842, "hotel", "hotel"),
    (843, "hicieron", "they did"),
    (844, "ten", "have (command)"),
    (845, "temo", "I fear"),
    (846, "señal", "signal"),
    (847, "pelo", "hair"),
    (848, "llevo", "I carry, I take"),
    (849, "ayer", "yesterday"),
    (850, "das", "you give"),
    (851, "nena", "baby girl"),
    (852, "servicio", "service"),
    (853, "tren", "train"),
    (854, "bonito", "pretty"),
    (855, "mes", "month"),
    (856, "tendrá", "will have"),
    (857, "tendrás", "you will have"),
    (858, "edad", "age"),
    (859, "ellas", "they (feminine)"),
    (860, "hermosa", "beautiful"),
    (861, "honor", "honor"),
    (862, "simplemente", "simply"),
    (863, "llamas", "you call, flames"),
    (864, "tengas", "you have (subjunctive)"),
    (865, "corre", "runs"),
    (866, "baja", "low (feminine), goes down"),
    (867, "sol", "sun"),
    (868, "siéntate", "sit down"),
    (869, "dan", "they give"),
    (870, "humano", "human"),
    (871, "divertido", "fun"),
    (872, "sexo", "sex"),
    (873, "vuelto", "returned"),
    (874, "peligro", "danger"),
    (875, "mesa", "table"),
    (876, "siguiente", "next"),
    (877, "hablo", "I speak"),
    (878, "disculpa", "excuse me, sorry"),
    (879, "decirme", "to tell me"),
    (880, "caja", "box"),
    (881, "negocios", "businesses"),
    (882, "misión", "mission"),
    (883, "silencio", "silence"),
    (884, "sale", "goes out"),
    (885, "llegado", "arrived"),
    (886, "estaría", "would be"),
    (887, "regreso", "return"),
    (888, "media", "half, average"),
    (889, "estan", "they are (misspelling)"),
    (890, "propio", "own"),
    (891, "oro", "gold"),
    (892, "enseguida", "right away"),
    (893, "linda", "pretty (feminine)"),
    (894, "prometo", "I promise"),
    (895, "esposo", "husband"),
    (896, "norte", "north"),
    (897, "hubo", "there was"),
    (898, "juro", "I swear"),
    (899, "muerta", "dead (feminine)"),
    (900, "interesante", "interesting"),
    (901, "pensaba", "was thinking"),
    (902, "busca", "looks for, search"),
    (903, "terminar", "to finish"),
    (904, "tendré", "I will have"),
    (905, "completamente", "completely"),
    (906, "cita", "appointment, quote"),
    (907, "siete", "seven"),
    (908, "cumpleaños", "birthday"),
    (909, "abogado", "lawyer"),
    (910, "alrededor", "around"),
    (911, "cerebro", "brain"),
    (912, "porqué", "why (noun)"),
    (913, "llave", "key"),
    (914, "santo", "saint"),
    (915, "hermoso", "beautiful (masculine)"),
    (916, "necesario", "necessary"),
    (917, "edificio", "building"),
    (918, "irnos", "to leave"),
    (919, "aun", "even"),
    (920, "tendremos", "we will have"),
    (921, "vayas", "you go (subjunctive)"),
    (922, "doy", "I give"),
    (923, "trae", "brings"),
    (924, "salió", "went out"),
    (925, "ley", "law"),
    (926, "ahi", "there (misspelling)"),
    (927, "verdadero", "true"),
    (928, "pelea", "fight"),
    (929, "banco", "bank, bench"),
    (930, "terrible", "terrible"),
    (931, "calma", "calm"),
    (932, "cena", "dinner"),
    (933, "daré", "I will give"),
    (934, "gobierno", "government"),
    (935, "comprar", "to buy"),
    (936, "creen", "they believe"),
    (937, "sargento", "sergeant"),
    (938, "destino", "destiny"),
    (939, "existe", "exists"),
    (940, "hacía", "was doing, was making"),
    (941, "novio", "boyfriend"),
    (942, "sala", "room, hall"),
    (943, "través", "through"),
    (944, "regalo", "gift"),
    (945, "iglesia", "church"),
    (946, "decía", "was saying"),
    (947, "cualquiera", "anyone"),
    (948, "excelente", "excellent"),
    (949, "esperen", "wait (plural)"),
    (950, "deseo", "I wish, desire"),
    (951, "alma", "soul"),
    (952, "diablo", "devil"),
    (953, "deje", "leave (formal)"),
    (954, "cuántos", "how many"),
    (955, "espada", "sword"),
    (956, "estábamos", "we were"),
    (957, "carne", "meat"),
    (958, "maravilloso", "wonderful"),
    (959, "vidas", "lives"),
    (960, "sucedió", "happened"),
    (961, "oí", "I heard"),
    (962, "peligroso", "dangerous"),
    (963, "dirección", "address, direction"),
    (964, "libertad", "freedom"),
    (965, "jesús", "Jesus"),
    (966, "ocurrió", "occurred"),
    (967, "veré", "I will see"),
    (968, "sueños", "dreams"),
    (969, "pudiera", "could (subjunctive)"),
    (970, "detective", "detective"),
    (971, "sorpresa", "surprise"),
    (972, "tuya", "yours (feminine)"),
    (973, "pies", "feet"),
    (974, "club", "club"),
    (975, "terminado", "finished"),
    (976, "infierno", "hell"),
    (977, "creía", "believed"),
    (978, "luna", "moon"),
    (979, "salvar", "to save"),
    (980, "carta", "letter, card"),
    (981, "estés", "you be (subjunctive)"),
    (982, "cielos", "heavens"),
    (983, "teniente", "lieutenant"),
    (984, "encuentra", "finds"),
    (985, "veamos", "let's see"),
    (986, "quise", "I wanted"),
    (987, "escúchame", "listen to me"),
    (988, "necesitan", "they need"),
    (989, "ambos", "both"),
    (990, "decisión", "decision"),
    (991, "enemigo", "enemy"),
    (992, "hicimos", "we did"),
    (993, "dulce", "sweet"),
    (994, "pruebas", "tests, proofs"),
    (995, "querías", "you wanted"),
    (996, "abuelo", "grandfather"),
    (997, "totalmente", "totally"),
    (998, "mirando", "looking"),
    (999, "vayan", "go (subjunctive plural)"),
    (1000, "carrera", "career, race"),
]

def add_all_1000_words():
    """Add/update all 1000 high-frequency words"""
    db: Session = SessionLocal()
    try:
        added_count = 0
        updated_count = 0
        skipped_count = 0
        seen_words = set()
        
        for rank, spanish, english in ALL_1000_WORDS:
            # Skip excluded standalone grammar words
            if spanish in EXCLUDED_STANDALONE:
                skipped_count += 1
                continue
                
            # Skip duplicates within the list
            if spanish in seen_words:
                skipped_count += 1
                continue
            seen_words.add(spanish)
            
            word_id = f"hf_{spanish}"
            existing_word = db.query(Word).filter(Word.id == word_id).first()
            
            if existing_word:
                existing_word.word_category = 'high_frequency'
                existing_word.frequency_rank = rank
                if not existing_word.english or existing_word.english == "":
                    existing_word.english = english
                updated_count += 1
            else:
                new_word = Word(
                    id=word_id,
                    spanish=spanish,
                    english=english,
                    word_category='high_frequency',
                    frequency_rank=rank
                )
                db.add(new_word)
                added_count += 1
            
            if (added_count + updated_count) % 50 == 0:
                db.commit()
        
        db.commit()
        print(f"✅ Added {added_count} high-frequency words")
        print(f"✅ Updated {updated_count} existing words")
        print(f"⚠️  Skipped {skipped_count} words (excluded grammar words or duplicates)")
        print(f"📊 Total processed: {added_count + updated_count} words")
        
    except Exception as e:
        db.rollback()
        print(f"❌ Error: {e}")
        import traceback
        traceback.print_exc()
        raise
    finally:
        db.close()

if __name__ == "__main__":
    add_all_1000_words()

